spring.main.banner-mode=off

#server
#server.error.whitelabel.enabled=false

# create and drop tables and sequences
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# H2 in-memory database settings (local development)
spring.datasource.url=jdbc:h2:mem:cardb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Enable H2 console for development
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# HikariCP settings
# spring.datasource.hikari.*
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.=info
